'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Table
    Public Property Id As Integer
    Public Property 顧客名 As String
    Public Property フリガナ As String
    Public Property 性別 As String
    Public Property 会社名 As String
    Public Property 住所 As String

End Class
